#!/bin/bash
scriptdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
dump_dir="${scriptdir}/dump"
mkdir -p "${dump_dir}"

cmd="${1}"
conf="${2}"
dump="${3}"

debug="false"
for val in "$@"; do
    if [[ "${val}" =~ ^-+(d|debug)$ ]]; then
        debug="true"
    fi
done

function rcmd() {
    if [[ "${debug}" != "false" ]]; then
        echo -e "\n\033[0;93m${1}\033[0m"
    else
        eval "${1}"
    fi
}

function display_help() {
    cat "${scriptdir}/doc/help.txt"
    echo ""
    exit 1
}
if [[ -z "${conf}" ]]; then
    display_help
fi

function gk() {
    cat "${conf}" |
        grep -E "^${1}" | grep -Po "[^=]+$" | grep -Po "(?<=\").*(?=\")"
}

pg_args=""
pg_pass="$(gk "pg_pass")"
if [[ -n "${pg_pass}" ]]; then
    export PGPASSWORD="${pg_pass}"
    pg_args+="-w "
fi
pg_args+="-h $(gk "pg_host") -p $(gk "pg_port") -U $(gk "pg_user") $(gk "pg_db")"

function pull() {
    target_file="${dump_dir}/$(date +%Y%m%d_%H%M%S).sql.gz"
    rcmd "mkdir -p \"${dump_dir}\""
    rcmd "pg_dump ${pg_args} | gzip >\"${target_file}\""
}

function push() {
    rcmd "gunzip \"${dump}\" | psql ${pg_args}"
}

function drop() {
    if [[ "${debug}" == "false" ]]; then
        echo ""
        printf "You're about to overwrite your current database. "
        read -p "Sure to continue? y/n   " inp
        if [[ "${inp}" != "y" ]]; then
            echo -e "Abort.\n"
            exit
        fi
    fi
    rcmd "dropdb ${pg_args}"
}

function create() {
    rcmd "createdb ${push_args}"
}

function list() {
    rcmd "psql -l -t"
}

case "${cmd}" in
pull) pull ;;
push) push ;;
drop) drop ;;
list) list ;;
create) create ;;
*) display_help ;;
esac
